title: Jeremiah's Portfolio
profile_img: /assets/img/me.jpeg
icon_img: /assets/img/icon.webp

name: Jeremiah Ross
job: Full Stack Software Developer

address: San Antonio, Texas, USA
email: crosswolf.20work@gmail.com
linkedin_username: jeremiahross
github_username: crosswolfv1
resume_url: https://docs.google.com/document/d/16wGWkFsC6WEhqgbyu4SgoWdXSHLkV-LATSgrfsuTcJc/edit?usp=sharing

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag